name: Static Analysis

on:
  pull_request:
  push:
    branches:
      - 'main*'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    check:
        name: All
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'WordPress/block-interactivity-experiments' || github.event_name == 'pull_request' }}

        steps:
            - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

            - name: Use desired version of NodeJS
              uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
              with:
                node-version-file: '.nvmrc'
                cache: npm

            - name: Install dependencies
              run: npm ci

            # TODO: Lint JS too!
            - name: Check PHP coding standards (PHPCS)
              run: npm run lint:php
