name: Run unit tests

on: [push]

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test